"""
Weekly Digest — creates a GitHub Issue every Sunday summarising the week's posts.
V2 feature: gives you a human-readable view of what was published and its engagement.
"""
import os
import sys
import json
import subprocess
from datetime import datetime, timedelta
from pathlib import Path

# Add scripts dir to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from history import load_history


def count_posts_this_week(posts_dir: Path) -> list[dict]:
    """Return a list of post metadata dicts for files from the last 7 days."""
    cutoff = datetime.now() - timedelta(days=7)
    results = []

    for md_file in sorted(posts_dir.glob("*.md")):
        # Files named YYYY-MM-DD-N.md or YYYY-MM-DD.md
        stem = md_file.stem
        date_part = stem[:10]
        try:
            file_date = datetime.strptime(date_part, "%Y-%m-%d")
        except ValueError:
            continue
        if file_date >= cutoff:
            content = md_file.read_text(encoding="utf-8")
            # Extract first non-empty line after frontmatter
            parts = content.split("---")
            body = "---".join(parts[2:]).strip() if len(parts) >= 3 else content
            first_line = next((l.strip() for l in body.splitlines() if l.strip()), "")
            results.append({
                "date": date_part,
                "file": md_file.name,
                "hook": first_line[:120],
                "status": "posted" if "status: posted" in content else "pending",
            })

    return results


def build_digest_body(posts: list[dict], history: dict) -> str:
    """Build the markdown body for the weekly GitHub Issue."""
    today = datetime.now().strftime("%Y-%m-%d")
    week_start = (datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d")

    lines = [
        f"## 📬 Weekly LinkedIn Post Digest",
        f"**Period**: {week_start} → {today}",
        f"**Posts generated this week**: {len(posts)}",
        "",
        "---",
        "",
    ]

    if not posts:
        lines.append("_No posts generated this week._")
    else:
        lines.append("### Posts")
        lines.append("")
        for p in posts:
            status_emoji = "✅" if p["status"] == "posted" else "⏳"
            lines.append(f"- {status_emoji} **{p['date']}** — {p['hook']}")
        lines.append("")

    # Engagement summary from history
    history_posts = history.get("posts", [])
    cutoff_str = (datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d %H:%M:%S")
    recent_with_metrics = [
        p for p in history_posts
        if p.get("posted_at", "") >= cutoff_str and (
            p.get("metrics", {}).get("likes", 0) + p.get("metrics", {}).get("comments", 0) > 0
        )
    ]

    if recent_with_metrics:
        lines += [
            "### 📊 Engagement (last 7 days)",
            "",
        ]
        for p in sorted(recent_with_metrics, key=lambda x: x.get("metrics", {}).get("likes", 0), reverse=True):
            m = p.get("metrics", {})
            lines.append(f"- **{p.get('title', 'Unknown')[:80]}** — 👍 {m.get('likes', 0)} likes, 💬 {m.get('comments', 0)} comments")
        lines.append("")

    lines += [
        "---",
        "",
        "_This issue was auto-generated by the LinkedIn Automation weekly digest workflow._",
    ]

    return "\n".join(lines)


def create_github_issue(title: str, body: str) -> bool:
    """Create a GitHub Issue using the GH CLI."""
    try:
        result = subprocess.run(
            ["gh", "issue", "create",
             "--title", title,
             "--body", body,
             "--label", "digest"],
            capture_output=True, text=True, check=False
        )
        if result.returncode == 0:
            print(f"[SUCCESS] Weekly digest issue created: {result.stdout.strip()}")
            return True
        else:
            # Fallback: gh might not be able to add unseen labels, retry without --label
            result2 = subprocess.run(
                ["gh", "issue", "create",
                 "--title", title,
                 "--body", body],
                capture_output=True, text=True, check=False
            )
            if result2.returncode == 0:
                print(f"[SUCCESS] Weekly digest issue created (no label): {result2.stdout.strip()}")
                return True
            print(f"[ERROR] gh issue create failed: {result2.stderr}")
            return False
    except FileNotFoundError:
        print("[ERROR] 'gh' CLI not found. Make sure it is installed in the CI environment.")
        return False


def main():
    posts_dir = Path(__file__).parent.parent / "posts"
    history = load_history()

    posts_this_week = count_posts_this_week(posts_dir)
    body = build_digest_body(posts_this_week, history)

    today = datetime.now().strftime("%Y-%m-%d")
    title = f"📬 Weekly Digest — {today}"

    print(f"[INFO] Creating weekly digest issue: '{title}'")
    print(f"[INFO] Posts this week: {len(posts_this_week)}")
    create_github_issue(title, body)


if __name__ == "__main__":
    main()
